defaults:
  - /archive/uncertain_configs/dreamer_vla_libero_goal_rynn_dino_wm_dense_chunk
  - _self_

training:
  out_dir: /mnt/data/spoil/workspace/DreamerVLA/data/outputs/dreamervla/actor_critic_ppo/libero_object/manual

init:
  vla_ckpt_path: /mnt/data/spoil/workspace/DreamerVLA/data/ckpts/VLA_model_256/libero_object
  world_model_state_ckpt: /mnt/data/spoil/workspace/DreamerVLA/data/outputs/worldmodel/rynn_dino_wm_action_hidden/libero_object/manual/ckpt/latest.ckpt

dataset:
  hdf5_dir: /mnt/data/spoil/workspace/DreamerVLA/data/processed_data/libero_object_no_noops_t_256_pi06_remaining_reward
  hidden_dir: /mnt/data/spoil/workspace/DreamerVLA/data/processed_data/libero_object_no_noops_t_256_pi0_legacy_action_hidden_vla_policy_h2
  expected_model_path: /mnt/data/spoil/workspace/DreamerVLA/data/ckpts/VLA_model_256/libero_object
  expected_time_horizon: 5

world_model:
  obs_dim: 35840
  token_count: 35

policy:
  hidden_dim: 35840
  time_horizon: 5

