defaults:
  - /world_model_dinowm_chunk
  - _self_

training:
  out_dir: /mnt/data/spoil/workspace/DreamerVLA/data/outputs/worldmodel/rynn_dino_wm_action_hidden/libero_spatial/manual

dataset:
  hdf5_dir: /mnt/data/spoil/workspace/DreamerVLA/data/processed_data/libero_spatial_no_noops_t_256_pi06_remaining_reward
  hidden_dir: /mnt/data/spoil/workspace/DreamerVLA/data/processed_data/libero_spatial_no_noops_t_256_pi0_legacy_action_hidden_vla_policy_h2
  expected_model_path: /mnt/data/spoil/workspace/DreamerVLA/data/ckpts/VLA_model_256/libero_spatial
  expected_time_horizon: 10

world_model:
  obs_dim: 71680
  token_count: 70

