# @package _global_
defaults:
  - rynnvla_action_head
  - _self_

training:
  out_dir: ${oc.env:OUT_DIR,${oc.env:DVLA_DATA_ROOT,${oc.env:DVLA_ROOT,.}/data}/outputs/vla/rynnvla_full_finetune/${now:%Y%m%d_%H%M%S}}
  distributed_strategy: ddp
  enable_activation_checkpointing: false
  train_encoder_backbone: true
  vla_train_action_head_only: false

dataloader:
  num_workers: 8
  pin_memory: true
  persistent_workers: true

optim:
  vla:
    lr: 2.0e-6
