# @package _global_
input_dir: ${oc.env:DVLA_DATA_ROOT,${oc.env:DVLA_ROOT,.}/data}/processed_data/OpenVLA_Onetraj_LIBERO_libero_goal/no_noops_t_256
output_dir: ${oc.env:DVLA_DATA_ROOT,${oc.env:DVLA_ROOT,.}/data}/processed_data/OpenVLA_Onetraj_LIBERO_libero_goal/no_noops_t_256_remaining_reward
metainfo_json: null
success_threshold: 0.5
failure_value: 0.0
min_value: 0.0
max_value: 1.0
compression: none
max_files: null
overwrite: false
