defaults:
  - archive/libero10_legacy/dreamerv3_token_libero_10
  - _self_

_target_: src.workspace.TokenWMWorkspace
training:
  out_dir: /mnt/data/spoil/workspace/DreamerVLA/data/outputs/worldmodel/dreamerv3_token/dreamerv3_token_libero_goal

dataset:
  vocab_config_path: /mnt/data/spoil/workspace/DreamerVLA/data/ckpts/VLA_model_256/libero_goal/config.json
