hdf5_dir: ${oc.env:DVLA_DATA_ROOT,${oc.env:DVLA_ROOT,.}/data}/processed_data/libero_goal/no_noops_t_256
out_dir: null
image_keys: [agentview_rgb, eye_in_hand_rgb]
prompt_style: vla_policy
history: 2
include_state: true
rotate_images_180: true
hidden_key: obs_embedding
obs_hidden_source: action_query
save_actor_sequence: false
save_action_hidden: false
action_trigger_token_id: 10004
chunk_size: 16
output_dtype: float16
compression: none
max_files: null
max_demos_per_file: null
overwrite: false
no_global_progress: false
model_path: ${oc.env:DVLA_DATA_ROOT,${oc.env:DVLA_ROOT,.}/data}/checkpoints/VLA_model_256/libero_goal
encoder_state_ckpt: null
tokenizer_path: ${oc.env:DVLA_DATA_ROOT,${oc.env:DVLA_ROOT,.}/data}/checkpoints/models--Alpha-VLLM--Lumina-mGPT-7B-768
text_tokenizer_path: ${oc.env:DVLA_DATA_ROOT,${oc.env:DVLA_ROOT,.}/data}/checkpoints/chameleon/tokenizer/text_tokenizer.json
chameleon_vqgan_config: ${oc.env:DVLA_DATA_ROOT,${oc.env:DVLA_ROOT,.}/data}/checkpoints/chameleon/tokenizer/vqgan.yaml
chameleon_vqgan_ckpt: ${oc.env:DVLA_DATA_ROOT,${oc.env:DVLA_ROOT,.}/data}/checkpoints/chameleon/tokenizer/vqgan.ckpt
resolution: 256
action_dim: 7
time_horizon: 5
token_dim: 4096
action_head_type: legacy
pool: mean
