openvla_oft_dir: ${oc.env:DVLA_ROOT,.}/dreamervla/models/embodiment/openvla_oft
hdf5_dir: ${oc.env:DVLA_DATA_ROOT,${oc.env:DVLA_ROOT,.}/data}/processed_data/OpenVLA_Onetraj_LIBERO_libero_goal/no_noops_t_256_remaining_reward
out_input_token_dir: ${oc.env:DVLA_DATA_ROOT,${oc.env:DVLA_ROOT,.}/data}/processed_data/OpenVLA_Onetraj_LIBERO_libero_goal/no_noops_t_256_oft_input_token_embedding_vla_policy_h1
obs_hidden_source: input_token_embedding
oft_ckpt: ${oc.env:DVLA_DATA_ROOT,${oc.env:DVLA_ROOT,.}/data}/checkpoints/Openvla-oft-SFT-traj1/Openvla-oft-SFT-libero-goal-traj1
unnorm_key: libero_goal_no_noops
policy_mode: discrete
image_keys: [agentview_rgb]
num_images_in_input: 1
include_state: false
center_crop: true
history: 1
rotate_images_180: true
resolution: 256
prompt_style: vla_policy
load_in_8bit: false
load_in_4bit: false
hidden_key: obs_embedding
time_horizon: 8
action_dim: 7
patches_per_image: 256
token_dim: 4096
chunk_size: 1
output_dtype: float16
max_files: null
max_demos_per_file: null
overwrite: false
fake_oft_components: false
fake_num_patches: 4
