task: null
resolution: null
tokenizer_path: ${oc.env:DVLA_DATA_ROOT,${oc.env:DVLA_ROOT,.}/data}/checkpoints/models--Alpha-VLLM--Lumina-mGPT-7B-768
in_filename_dir: ${oc.env:DVLA_DATA_ROOT,${oc.env:DVLA_ROOT,.}/data}/processed_data/libero_goal/convs
out_root: ${oc.env:DVLA_DATA_ROOT,${oc.env:DVLA_ROOT,.}/data}/processed_data/libero_goal/tokens
his: 2
len_action: 5
with_state: false
img_names: [imgs_third_view]
num_procs: 32
gpu_devices: "0,1,2,3"
overwrite: false
