defaults:
  - chameleon_latent_action_wm_libero_10
  - _self_

training:
  out_dir: /home/user01/liops/workspace/DreamerVLA/data/outputs/worldmodel/chameleon_latent_action_wm/chameleon_latent_action_wm_libero_goal

init:
  vla_ckpt_path: /home/user01/liops/workspace/DreamerVLA/data/ckpts/VLA_model_256/libero_goal

encoder:
  model_path: /home/user01/liops/workspace/DreamerVLA/data/ckpts/VLA_model_256/libero_goal
  time_horizon: 5
