defaults:
  - dreamerv3_token_libero_10
  - _self_

training:
  out_dir: /home/user01/liops/workspace/DreamerVLA/data/outputs/worldmodel/dreamerv3_token/dreamerv3_token_libero_goal

dataset:
  vocab_config_path: /home/user01/liops/workspace/DreamerVLA/data/ckpts/VLA_model_256/libero_goal/config.json
