defaults:
  - dreamer_vla_libero_10_dreamerv3_token_actor
  - _self_

training:
  out_dir: /home/user01/liops/workspace/DreamerVLA/data/outputs/dreamervla/dreamerv3_token_actor_libero_goal

init:
  encoder_state_ckpt: null
