defaults:
  - pretokenize_vla_libero_goal
  - _self_

training:
  out_dir: /home/user01/liops/workspace/DreamerVLA/data/outputs/vla/pretokenize_vla_goal_pi0_query
  vla_train_action_head_only: true

encoder:
  action_head_type: pi0_query
