_target_: src.workspace.semantic_bottleneck_wm_workspace.SemanticBottleneckWMWorkspace

training:
  out_dir: /home/user01/liops/workspace/DreamerVLA/data/outputs/worldmodel/semantic_bottleneck_wm/semantic_bottleneck_wm_libero_goal
  device: cuda:0
  distributed_strategy: ddp
  data_parallel: false
  seed: 7
  max_steps: 10000
  num_epochs: null
  log_every: 20
  save_every: 1000
  tqdm_interval_sec: 1.0
  resume: false
  resume_path: null
  resume_strict: true
  resume_skip_optimizer: false
  save_final: true

dataset:
  _target_: src.dataloader.libero_pixel_rynn_hidden_sequence_dataset.LIBEROPixelRynnHiddenSequenceDataset
  hdf5_dir: /home/user01/liops/workspace/DreamerVLA/data/processed_data/libero_goal_no_noops_t_256
  hidden_dir: /home/user01/liops/workspace/DreamerVLA/data/processed_data/libero_goal_no_noops_t_256_rynn_hidden_goal_h5_epoch000
  expected_model_path: /home/user01/liops/workspace/DreamerVLA/data/ckpts/VLA_model_256/libero_goal
  expected_encoder_state_ckpt: /home/user01/liops/workspace/DreamerVLA/data/outputs/vla/pretokenize_vla/pretokenize_vla_libero_goal_libero_goal_h5_20260508_060320/checkpoints/goal_h5_epoch000_train_vla_loss_1p323.ckpt
  expected_time_horizon: 5
  sequence_length: 32
  image_size: 64
  image_keys: [agentview_rgb, eye_in_hand_rgb]
  hidden_key: obs_embedding
  load_actor_sequence: false
  stride: 1
  max_files: null
  max_demos_per_file: null
  max_windows: null

dataloader:
  batch_size: 256
  num_workers: 4
  pin_memory: false
  drop_last: true
  persistent_workers: true
  prefetch_factor: 1
  multiprocessing_context: forkserver

world_model:
  _target_: src.models.world_model.semantic_bottleneck.SemanticBottleneckRSSMWorldModel
  sem_dim: 4096
  latent_dim: 32
  deter: 256
  action_dim: 7
  hidden: 256
  bottleneck_hidden: 512
  bottleneck_layers: 2
  rssm_layers: 2
  reward_loss: mse
  reward_scale: 1.0
  continue_scale: 1.0
  dyn_scale: 1.0
  bottleneck_kl_scale: 0.001
  actor_input_dim: 288

optim:
  lr: 3e-4
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  weight_decay: 0.0
  warmup: 500
  grad_clip: 100.0

viz:
  enabled: false
