# @package _global_
defaults:
  - _self_
  - VLA: null
  - worldmodel: null
  - classifier: null
  - dreamervla: null
  - evaluation: null
  - logger: tensorboard_wandb
  - experiment: openvla_onetraj_libero_cotrain_ray
