# @package _global_
defaults:
  - _self_
  - VLA: null
  - worldmodel: null
  - classifier: null
  - dreamervla: null
  - evaluation: null
  - logger: tensorboard
  - experiment: world_model_dinowm_chunk
