#!/usr/bin/env bash
# Train DreamerV3 WM on pi0 action-query hidden observations.
#
# The sidecar obs_embedding is the flattened output of the pi0 action-query
# transformer, not a pooled VLA hidden state.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/env_libero_goal_pi0_query.sh"

CONFIG_NAME="${CONFIG_NAME:-rynn_backbone_dreamerv3_action_hidden_wm_libero_goal_precomputed}"
WM_KIND="${WM_KIND:-action_hidden}"
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}"
NUM_GPUS="${NUM_GPUS:-4}"
MASTER_PORT="${MASTER_PORT:-29563}"
ACTION_HIDDEN_DDP="${ACTION_HIDDEN_DDP:-1}"
BATCH_SIZE="${BATCH_SIZE:-96}"
NUM_WORKERS="${NUM_WORKERS:-2}"
PREFETCH_FACTOR="${PREFETCH_FACTOR:-1}"
PIN_MEMORY="${PIN_MEMORY:-false}"
PERSISTENT_WORKERS="${PERSISTENT_WORKERS:-true}"
DATALOADER_MP_CONTEXT="${DATALOADER_MP_CONTEXT:-forkserver}"
TIMESTAMP="${TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}"
RUN_TAG="${RUN_TAG:-pi0_action_hidden_ddp_precomputed_bs${BATCH_SIZE}_nw${NUM_WORKERS}_gpu${CUDA_VISIBLE_DEVICES//,/}_viz}"
OUT_DIR_BASE="${OUT_DIR_BASE:-${PROJECT_ROOT}/data/outputs/worldmodel/action_hidden_dreamerv3_wm}"

ACTION_HIDDEN_DIR="${ACTION_HIDDEN_DIR:-${RYNN_WM_HIDDEN_DIR:-${PI0_ACTION_HIDDEN_DIR}}}"
OBS_HIDDEN_SOURCE="${OBS_HIDDEN_SOURCE:-action_query}"
ACTION_HIDDEN_EXPECTED_OBS_HIDDEN_SOURCE="${ACTION_HIDDEN_EXPECTED_OBS_HIDDEN_SOURCE:-action_query}"
ACTION_HIDDEN_EXPECTED_PROMPT_STYLE="${ACTION_HIDDEN_EXPECTED_PROMPT_STYLE:-vla_policy}"
ACTION_HIDDEN_EXPECTED_HISTORY="${ACTION_HIDDEN_EXPECTED_HISTORY:-2}"
ACTION_HIDDEN_EXPECTED_INCLUDE_STATE="${ACTION_HIDDEN_EXPECTED_INCLUDE_STATE:-true}"
ACTION_HIDDEN_EXPECTED_ROTATE_IMAGES_180="${ACTION_HIDDEN_EXPECTED_ROTATE_IMAGES_180:-true}"
ACTION_HIDDEN_WM_OBS_DIM="${ACTION_HIDDEN_WM_OBS_DIM:-5120}"
LOAD_ACTOR_SEQUENCE="${LOAD_ACTOR_SEQUENCE:-false}"
ACTOR_SEQUENCE_LENGTH="${ACTOR_SEQUENCE_LENGTH:-0}"
FULL_HIDDEN_REC_SCALE="${FULL_HIDDEN_REC_SCALE:-0.0}"

export CONFIG_NAME WM_KIND CUDA_VISIBLE_DEVICES NUM_GPUS MASTER_PORT ACTION_HIDDEN_DDP
export BATCH_SIZE NUM_WORKERS PREFETCH_FACTOR PIN_MEMORY PERSISTENT_WORKERS DATALOADER_MP_CONTEXT
export TIMESTAMP RUN_TAG OUT_DIR_BASE
export VLA_INIT_CKPT VLA_STATE_CKPT ENCODER_STATE_CKPT ACTION_HIDDEN_DIR HDF5_DIR ACTION_HORIZON TIME_HORIZON
export OBS_HIDDEN_SOURCE ACTION_HIDDEN_EXPECTED_OBS_HIDDEN_SOURCE ACTION_HIDDEN_EXPECTED_PROMPT_STYLE ACTION_HIDDEN_EXPECTED_HISTORY
export ACTION_HIDDEN_EXPECTED_INCLUDE_STATE ACTION_HIDDEN_EXPECTED_ROTATE_IMAGES_180 ACTION_HIDDEN_WM_OBS_DIM
export LOAD_ACTOR_SEQUENCE ACTOR_SEQUENCE_LENGTH FULL_HIDDEN_REC_SCALE

exec "${SCRIPT_DIR}/train_wm.sh" "$@"
